In [2]:
import numpy as np

In [3]:
def sigmoide(x):
    return (1.0 /( 1 + np.exp(-x)))
def sigmoidePrime(x):
    return sigmoid(x) * (1 - sigmoide(x))

In [4]:
class Neural_Network:
    
    def __init__(self,input,output,hiddenL,fonction,fonctionPrime):
        self.input = input
        self.output= output
        self.hiddenL= hiddenL
        self.w1 = np.random.randn(input,hiddenL)
        self.w2 = np.random.randn(hiddenL,output)
        self.fonction=fonction
        self.fonctionPrime=fonctionPrime
        
    def forward(self,datax):
        self.z2 = np.dot(datax,self.w1)
        self.a2 = self.fonction(self.z2)
        
        self.z3 = np.dot(self.a2,self.w2)
        yhat = self.fonction(self.z3)
        
           
        return yhat
        
        
        def constFunctionPrime(self,x,y):
            self.yHat = self.forward(x)
            delta3 = np.multiply(-(y-self.yhat), self.fonctionPrime(self.z3))
            djdw2 = np.dot(self.a2.T,delta3)
        
            delta2 = np.dot(delta3, self.w2.T) * self.fonctionPrime(self.z2)
            djdw1 = np.dot(x.T,delta2)
            
            return djw1,djdw2
            

In [5]:
nn1 = Neural_Network(2,1,3,sigmoide,sigmoidePrime)

In [6]:
x = np.random.randn(3,2)
x

array([[ 0.71093535,  0.87964579],
       [ 1.12933789,  0.6263458 ],
       [ 1.22596127, -0.49533667]])

In [7]:
nn1.forward(x) # tooo bad 

array([[ 0.86553981],
       [ 0.87135993],
       [ 0.83909374]])

In [8]:
nn1.w1.ravel()

array([-1.66731396,  0.7784744 ,  1.23586208,  0.43129841, -0.29176848,
        1.32325285])

In [9]:
nn1.w1

array([[-1.66731396,  0.7784744 ,  1.23586208],
       [ 0.43129841, -0.29176848,  1.32325285]])

In [11]:
nn1.w2.ravel()

array([ 0.31860689,  0.75136901,  1.5055213 ])

In [13]:
np.concatenate((nn1.w1.ravel(),nn1.w2.ravel()))

array([-1.66731396,  0.7784744 ,  1.23586208,  0.43129841, -0.29176848,
        1.32325285,  0.31860689,  0.75136901,  1.5055213 ])